### ISSUE TITLE
Error: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Chloezhang96** [youngkyung/SynthText_kr#1]
Hi YoungKyung, 
I'm running the codes on python 3.6 on Linux. I couldn't solve one error from colorize3_poisson.py: 
Traceback (most recent call last):
File "gen.py", line 140, in 
main(args.viz)
File "gen.py", line 95, in main
RV3 = RendererV3(DATA_PATH,max_time=SECS_PER_IMG)
File "/home/yuxin/example/SynthText/synthgen.py", line 368, in init
self.colorizer = Colorize(data_dir)
File "/home/yuxin/example/SynthText/colorize3_poisson.py", line 182, in init
self.font_color = FontColor(col_file = osp.join(model_dir, 'models/colors_news.cp)
File "/home/yuxin/example/SynthText/colorize3_poisson.py", line 69, in init
self.colorRGB = cp.load(f)
TypeError: a bytes-like object is required, not 'str'

I tried different approaches but still got different errors: 
1. with open(char_freq_path,'rb') as f:
error: No module named 'numpy.core.multiarray\r'
2. self.char_freq = cp.load(f,encoding='latin-1')
error: a bytes-like object is required, not'str'
3.   u = pickle._Unpickler(f)
     u.encoding = 'latin1'
     p = u.load()
     p = cp.load(f)
     self.colorsRGB = p
error: Assertion error 

Can you please tell how to solve it? Thank you!

**Comment by youngkyung** [comment]
In the original version(English), there was a character frequency file but in Korean language which is my version, there's no file. So I remember that I commented out that part.

So please comment out the codes related to that file. If you keep having the same error, can you try the code in Python 2 version?
