### ISSUE TITLE
Could you share fonts, processed images, and texts?

### ISSUE THREAD

**Issue by ThisIsIsaac** [youngkyung/SynthText_kr#3]
I want to create character-labeled Korean data but I can't get access to the linked background images and fonts. Could you share the images and fonts or the results you have generated?

If there are other open-sourced datasets that we can use as inputs to the network, please share with us. 

Thanks a lot!

**Comment by youngkyung** [comment]
I updated the url from the original github repo like the following:
http://www.robots.ox.ac.uk/~vgg/data/scenetext/preproc/bg_img.tar.gz

Also, I'll share  some Korean fonts that you can download like the following:
https://koreaoffice-my.sharepoint.com/:f:/g/personal/ygseo_korea_edu/EvnQDCsjGMFGp8RIpoECvZUBtZ1FV1Wf7kUkRvz9kZqecg?e=QuQ21Z

If there's any other problems, let me know.
